"""Generate .github/copilot-instructions.md from distilled skills.

This closes the loop: skills extracted from past conversations are injected
back into the project so Copilot reads them automatically in every new session.
VS Code Copilot reads `.github/copilot-instructions.md` as custom instructions.
"""

from __future__ import annotations

from pathlib import Path

from .db import get_db

# Header so users know this file is auto-generated
HEADER = """\
<!-- Auto-generated by copilot-autoskill — do not edit manually.
     Regenerate with: autoskill inject -p {project_name}
     Last updated: {timestamp} -->

# Project Skills & Patterns

> These are reusable patterns distilled from past Copilot conversations.
> Copilot will use them as context in every chat session for this project.

"""


def load_project_skills(project_path: str, db_path=None) -> list[dict]:
    """Load all skills for a project from the database."""
    conn = get_db(db_path)
    rows = conn.execute(
        "SELECT id, title, description, steps, tags, obs_type, facts, concepts, "
        "files_read, files_modified, narrative FROM skills "
        "WHERE project_path = ? ORDER BY created_at ASC",
        (project_path,),
    ).fetchall()
    conn.close()
    return [dict(r) for r in rows]


def render_instructions(skills: list[dict], project_path: str) -> str:
    """Render skills into a copilot-instructions.md string."""
    import json as _json
    from datetime import datetime, timezone

    project_name = Path(project_path).name if project_path else "global"
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    content = HEADER.format(project_name=project_name, timestamp=now)

    def _fmt_json_list(val):
        if not val or val == "[]":
            return ""
        if isinstance(val, str):
            try:
                val = _json.loads(val)
            except (ValueError, TypeError):
                return val
        if isinstance(val, list):
            return "\n".join(f"- {item}" for item in val)
        return str(val)

    for skill in skills:
        title = skill.get("title", "Untitled")
        desc = skill.get("description", "")
        steps = skill.get("steps", "")
        tags = skill.get("tags", "")
        obs_type = skill.get("obs_type", "workflow")
        facts = _fmt_json_list(skill.get("facts", "[]"))
        concepts = _fmt_json_list(skill.get("concepts", "[]"))

        content += f"## {title}\n\n"
        content += f"**Type:** {obs_type}\n\n"
        if desc:
            content += f"{desc}\n\n"
        if tags:
            content += f"**Tags:** {tags}\n\n"
        if facts:
            content += f"**Key Facts:**\n{facts}\n\n"
        if steps:
            content += f"**Steps:**\n{steps}\n\n"
        if concepts:
            content += f"**Concepts:** {', '.join(_json.loads(skill.get('concepts', '[]'))) if isinstance(skill.get('concepts'), str) else ', '.join(skill.get('concepts', []))}\n\n"
        content += "---\n\n"

    return content


def inject(
    project_path: str,
    output: str | None = None,
    db_path=None,
) -> dict:
    """Generate copilot-instructions.md for a project.

    Returns dict with: path, skills_count, written (bool), content.
    """
    skills = load_project_skills(project_path, db_path=db_path)

    if not skills:
        return {"path": None, "skills_count": 0, "written": False, "content": ""}

    content = render_instructions(skills, project_path)

    # Determine output path
    if output:
        out_path = Path(output)
    else:
        out_path = Path(project_path) / ".github" / "copilot-instructions.md"

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(content)

    return {
        "path": str(out_path),
        "skills_count": len(skills),
        "written": True,
        "content": content,
    }
